from app.exceptions.base import BaseException


class DuplicatedUserException(BaseException):
    pass
